# Generated by Django 4.1.2 on 2024-06-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_adquisicion', models.DateField()),
                ('cantidad_total', models.IntegerField()),
            ],
        ),
    ]
