# Generated by Django 4.1.2 on 2024-06-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='productos',
            field=models.ManyToManyField(related_name='carritos', to='sistema.product'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='fecha_adquisicion',
            field=models.DateTimeField(),
        ),
    ]
