# Generated by Django 4.1.2 on 2024-06-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_carrito_productos_alter_carrito_fecha_adquisicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='fecha_adquisicion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
