# Generated by Django 4.1.2 on 2024-07-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_alter_carrito_fecha_adquisicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
